/* The sound inventory (sound pass, owner review 2026-09-29): every sound the game plays and every place that should have
 * one. The single source for docs/rebuild/HOLM_SOUND_INVENTORY.md (tools/sfx_inventory_doc.js writes its tables) and for
 * tools/test_sfx.js, which pins that each sound exists (src/sfx_recipes.js) and is wired (each `wired` entry is a file and a
 * substring that must be in it; the call reaches the recipe through the Sfx method named in `via`).
 * status: 'replaced' (a sound existed and was redone), 'new' (there was no sound), 'not in game' (the sound exists and is
 * callable, but the game has no such action yet), 'candidate' (sound board only). */
'use strict';
const R=(group,event,sounds,via,wired,before,status,note)=>({group,event,sounds,via,wired,before,status,note:note||''});
module.exports=[
 // ---------------- UI
 R('UI','Side-panel tab click',['ui_tab'],'Sfx.tab()',[['src/game4_ui.js','Sfx.tab();']],'Sfx.click: a 700 Hz square tick','replaced'),
 R('UI','Button / menu row click',['ui_click'],'Sfx.click()',[['src/osrs_menu.js','Sfx.click()'],['src/game4_ui.js','Sfx.click();']],'a 700 Hz square tick','replaced'),
 R('UI','Window opens (smith grid, skill guide)',['ui_window_open'],'Sfx.windowOpen()',[['src/ui_smith_grid.js','Sfx.windowOpen()'],['src/ui_skill_guide.js','Sfx.windowOpen()']],'none','new'),
 R('UI','Window closes (bank, shop, map, guides)',['ui_window_close'],'Sfx.windowClose()',[['src/game4_ui.js','Sfx.windowClose();'],['src/ui_smith_grid.js','Sfx.windowClose()'],['src/ui_skill_guide.js','Sfx.windowClose()']],'none','new'),
 R('UI','Relief chart of Tutor\'s Holm opens',['ui_map_open'],'Sfx.mapOpen()',[['src/holm_guide_hall_interactions.js','Sfx.mapOpen()']],'the generic square click only (owner: "very plain")','replaced'),
 R('UI','World map opens / closes',['ui_map_open','ui_map_close'],'Sfx.mapOpen() / Sfx.mapClose()',[['src/game4_ui.js','Sfx.mapOpen();'],['src/game4_ui.js','Sfx.mapClose();']],'none','new'),
 R('UI','Dialogue: continue (each chat-box page)',['ui_dialogue'],'Sfx.dialogue()',[['src/game4_ui.js','Sfx.dialogue();']],'the square click','replaced'),
 R('UI','Level-up (the fireworks stay)',['level_up_a'],'Sfx.level() / LevelUpFX.sound()',[['src/game3_systems.js','Sfx.level();'],['src/fx_levelup.js','SfxLib.LEVEL_PICK']],'a firework whoosh, two pops, a crackle and a sine chime (owner: not the noise he wanted)','replaced'),
 R('UI','Level-up candidates B and C (sound board only)',['level_up_b','level_up_c'],'(sound board)',[['tools/sound_board.html','level_up_b']],'none','candidate'),
 R('UI','Lesson done / quest started or advanced',['quest_step'],'Sfx.quest()',[['src/game4_ui.js','Sfx.quest()'],['src/game3_systems.js','Sfx.quest();']],'two square-wave beeps','replaced'),
 R('UI','Quest complete',['quest_done'],'Sfx.questDone()',[['src/game3_systems.js','Sfx.questDone();']],'a square-wave triad','replaced'),
 R('UI','Coins (pick up, shop)',['coins'],'Sfx.coin()',[['src/game5_main.js','Sfx.coin();'],['src/ui_shop.js','Sfx.coin()']],'two sine blips','replaced'),
 // ---------------- items
 R('Items','Equip: tool (the hatchet, pickaxe)',['equip_tool'],'Sfx.equip(id)',[['src/game4_ui.js','Sfx.equip(s.id);']],'the square click (owner: "not an equip noise")','replaced'),
 R('Items','Equip: metal (blades, armour)',['equip_metal'],'Sfx.equip(id)',[['src/game4_ui.js','Sfx.equip(s.id);']],'the square click','replaced'),
 R('Items','Equip: wood (bow, staff, wooden shield)',['equip_wood'],'Sfx.equip(id)',[['src/game4_ui.js','Sfx.equip(s.id);']],'the square click','replaced'),
 R('Items','Equip: cloth',['equip_cloth'],'Sfx.equip(id)',[['src/game4_ui.js','Sfx.equip(s.id);']],'the square click','replaced'),
 R('Items','Equip: leather',['equip_leather'],'Sfx.equip(id)',[['src/game4_ui.js','Sfx.equip(s.id);']],'the square click','replaced'),
 R('Items','Equip: arrows',['equip_ammo'],'Sfx.equip(id)',[['src/game4_ui.js','Sfx.equip(s.id);']],'the square click','replaced'),
 R('Items','Unequip (menu Remove, paper doll, equipment row)',['unequip_metal','unequip_tool','unequip_wood','unequip_cloth','unequip_leather'],'Sfx.unequip(id)',
  [['src/osrs_menu_items.js','Sfx.unequip(v)'],['src/ui_osrs_kit.js','Sfx.unequip(v)'],['src/ui_medieval.js','Sfx.unequip(v)'],['src/game4_ui.js','Sfx.unequip(v)']],'the square click (the old equipment row: none)','replaced'),
 R('Items','Pick up an item',['pickup'],'Sfx.pickup()',[['src/game5_main.js','Sfx.pickup();'],['src/holm_teaching_kitchen_interactions.js','Sfx.pickup()'],['src/holm_guide_cellar.js','Sfx.pickup()']],'none (coins only)','new'),
 R('Items','Drop an item',['drop'],'Sfx.drop()',[['src/inventory_menu.js','Sfx.drop()']],'the square click','replaced'),
 R('Items','Bank opens',['bank_open'],'Sfx.bankOpen()',[['src/ui_shop.js','Sfx.bankOpen();']],'the coin blips','replaced'),
 R('Items','Bank: deposit / withdraw',['bank_deposit','bank_withdraw'],'Sfx.bankDeposit() / Sfx.bankWithdraw()',[['src/ui_shop.js','Sfx.bankDeposit();'],['src/ui_shop.js','Sfx.bankWithdraw();']],'none','new'),
 R('Items','Eat',['eat'],'Sfx.eat(id)',[['src/game4_ui.js','Sfx.eat(s.id);'],['src/combat_engine.js','Sfx.eat(s.id)']],'a low noise puff and a triangle blip','replaced'),
 R('Items','Drink (the coffee sips; ale, tea, potions through Sfx.eat)',['drink'],'Sfx.drink() / Sfx.eat(id)',[['src/coffee.js','Sfx.drink()'],['src/game3_systems.js',"?'drink':'eat'"]],'the eat sound','replaced'),
 // ---------------- doors
 R('Doors','Door opens (island gates, the bakehouse store door, the Guide House doors, mainland doors, Lastlight)',['door_open'],'Sfx.doorOpen(at)',
  [['src/holm_island_anim.js','S.doorOpen(d.center)'],['src/holm_arrival_qa.js','Sfx.doorOpen()'],['src/game4_ui.js','Sfx.doorOpen(door.position);'],['src/sfx_furnishings.js',"play('door_open')"]],'island gates: the chest creak (sawtooth); the Guide House doors: none; mainland: the square click; Lastlight: the click (SfxFurnishings.doorOpen was missing)','replaced'),
 R('Doors','Door closes',['door_close'],'Sfx.doorClose(at)',[['src/holm_island_anim.js','S.doorClose(d.center)'],['src/holm_arrival_qa.js','Sfx.doorClose()'],['src/game4_ui.js','Sfx.doorClose(door.position);']],'as above','replaced'),
 R('Doors','Door locked (a shut gate, a barred or bolted station)',['door_locked'],'Sfx.doorLocked(at)',[['src/holm_arrival_qa.js','Sfx.doorLocked(point)']],'none (chat line only)','new'),
 R('Doors','Iron gate (the bank vault) opens / closes',['gate_open','gate_close'],'Sfx.gateOpen(at) / Sfx.gateClose(at)',[['src/holm_island_anim.js','S.gateOpen('],['src/holm_island_anim.js','S.gateClose(']],'the chest creak','replaced'),
 R('Doors','Chest opens / closes (the storm-cellar reserve chest)',['chest_open','chest_close'],'SfxFurnishings.chestOpen/chestClose',[['src/sfx_furnishings.js',"play('chest_open')"],['src/sfx_furnishings.js',"play('chest_close'"]],'a sawtooth creak and a square latch','replaced'),
 R('Doors','Stairs (the Guide House flight)',['stairs'],'Sfx.stairs()',[['src/holm_arrival_qa.js','Sfx.stairs()']],'none','new'),
 // ---------------- skills
 R('Woodcutting','Chop: each stroke (on the swing, not the tick)',['chop'],'Sfx.chop() / HolmSound',[['src/game5_main.js','Sfx.chop();'],['src/holm_sound.js','s.play(k)']],'a noise burst and a triangle thump on the 0.6 s tick (the 0.78 s swing drifted off it)','replaced'),
 R('Woodcutting','Logs land in the pack',['log_land'],'Sfx.logLand()',[['src/game5_main.js','Sfx.logLand();']],'none','new'),
 R('Woodcutting','The tree tips (fall starts)',['tree_creak'],'Sfx.treeFall(at)',[['src/game5_main.js','Sfx.treeFall(a.obj.position);'],['src/game3_systems.js',"this.play('tree_creak'"]],'a low noise rumble','replaced'),
 R('Woodcutting','The tree lands',['tree_fall'],'Sfx.treeLand(at)',[['src/holm_island_anim.js','S.treeLand('],['src/game3_systems.js',"this.play('tree_fall'"]],'a low noise and sine thump','replaced'),
 R('Mining','Pickaxe strike (on the swing)',['mine'],'Sfx.mine() / HolmSound',[['src/game5_main.js','Sfx.mine();'],['src/holm_sound.js','s.play(k)']],'a 2.3 kHz square ping and a hiss (owner: "not correct")','replaced'),
 R('Mining','An ore chunk breaks off',['ore_break'],'Sfx.oreBreak()',[['src/game5_main.js','Sfx.oreBreak();']],'none (owner: should sound different)','new'),
 R('Mining','The rock runs empty',['rock_empty'],'Sfx.rockEmpty(at)',[['src/game5_main.js','Sfx.rockEmpty(a.obj.position);']],'none','new'),
 R('Mining','Prospecting',['prospect'],'Sfx.prospect()',[['src/game3_systems.js',"prospect(){ this.play('prospect')"]],'none','not in game','there is no Prospect option yet; call Sfx.prospect() when one is added'),
 R('Fishing','Net cast (the first tick and every roll)',['fish_cast'],'HolmFishing sfx(\'cast\')',[['src/holm_fishing.js',"cast:'fish_cast'"],['src/sfx_furnishings.js',"play('fish_cast')"]],'a band-passed noise and a second plish','replaced'),
 R('Fishing','Splash (junk on a roll, the frog)',['fish_splash'],'HolmFishing sfx(\'plish\')',[['src/holm_fishing.js',"plish:'fish_splash'"]],'band noise and a sine','replaced'),
 R('Fishing','Catch',['fish_catch'],'HolmFishing sfx(\'flop\')',[['src/holm_fishing.js',"flop:'fish_catch'"],['src/sfx_furnishings.js',"play('fish_catch')"]],'two low noise flops','replaced'),
 R('Fishing','A fish leaps (heard nearby only)',['fish_leap'],'HolmFishing sfx(\'leap\')',[['src/holm_fishing.js',"leap:'fish_leap'"]],'a low noise, heard anywhere on the island','replaced'),
 R('Firemaking','Tinderbox strike (every other tick of the kneel)',['fire_strike'],'Sfx.tinderStrike()',[['src/game5_main.js','Sfx.tinderStrike();']],'none','new'),
 R('Firemaking','The fire catches',['fire_catch'],'Sfx.fireCatch()',[['src/game5_main.js','Sfx.fireCatch();']],'none','new'),
 R('Firemaking','Crackle loop by any fire (campfires, hearths, the oven, torches)',['fire_loop'],'CozyFire',[['src/cozy_fire.js',"Sfx.loop('fire_loop')"]],'none','new'),
 R('Firemaking','Hearth crackle (warming at the storm-cellar hearth)',['fire_crackle'],'SfxFurnishings.hearthCrackle()',[['src/sfx_furnishings.js',"play('fire_crackle')"]],'square-wave snaps','replaced'),
 R('Cooking','Sizzle (each fish goes on the fire or range)',['cook_sizzle'],'Sfx.sizzle()',[['src/game5_main.js','Sfx.sizzle();']],'none','new'),
 R('Cooking','Cooked',['cook_done'],'Sfx.cookDone()',[['src/game5_main.js','Sfx.cookDone();']],'none','new'),
 R('Cooking','Burnt',['cook_burn'],'Sfx.burn()',[['src/game5_main.js','Sfx.burn();']],'none','new'),
 R('Cooking','Bake: bread into the oven',['bake_in'],'Sfx.bakeIn()',[['src/cooking_bread.js','Sfx.bakeIn();']],'none','new'),
 R('Cooking','Bake: the loaf comes out',['bake_done'],'Sfx.bakeDone()',[['src/cooking_bread.js','Sfx.bakeDone();']],'none','new'),
 R('Cooking','Mix the bread dough',['dough'],'Sfx.dough()',[['src/cooking_bread.js','Sfx.dough();']],'the square click','replaced'),
 R('Smithing','Smelt: the furnace roars (each stroke)',['smelt_roar'],'Sfx.furnace()',[['src/game5_main.js','Sfx.furnace();']],'none (a low noise at the bar)','new'),
 R('Smithing','Smelt: the bar comes out',['smelt_bar'],'Sfx.smelt()',[['src/game5_main.js','Sfx.smelt();']],'a low noise and a triangle','replaced'),
 R('Smithing','Hammer on anvil (each strike)',['anvil'],'Sfx.anvil()',[['src/holm_island_anim.js','S.anvil()'],['src/game3_systems.js',"this.play('anvil')"]],'a 2.35 kHz square clink','replaced'),
 R('Smithing','The item comes off the anvil',['smith_done'],'Sfx.smith()',[['src/game5_main.js','Sfx.smith();']],'a 1.85 kHz square tone','replaced'),
 R('Skills','Take / return a bucket',['bucket_take'],'Sfx.bucketTake()',[['src/holm_teaching_kitchen_interactions.js','Sfx.bucketTake()']],'the square click','replaced'),
 R('Skills','Fill a bucket: water / flour',['bucket_water','bucket_flour'],'Sfx.bucketFill(kind)',[['src/holm_teaching_kitchen_interactions.js','Sfx.bucketFill(label)']],'the square click','replaced'),
 R('Skills','Tie the rope to the shaft frame',['rope_tie'],'Sfx.ropeTie()',[['src/holm_shaft_rope.js','Sfx.ropeTie()']],'none','new'),
 R('Skills','Climb the rope (the quarry shaft)',['rope_climb'],'Sfx.ropeClimb()',[['src/holm_arrival_qa.js','Sfx.ropeClimb()']],'none','new'),
 R('Skills','Ladders up / down (every island ladder, the cellar hatch)',['ladder_up','ladder_down'],'Sfx.ladder(dir)',[['src/holm_arrival_qa.js','Sfx.ladder(up.y>player.position.y'],['src/holm_guide_cellar.js',"Sfx.ladder(c.down?'down':'up')"],['src/sfx_furnishings.js',"'ladder_up':'ladder_down'"]],'island: none; storm cellar: sawtooth creaks','replaced'),
 R('Skills','Pulley / windlass (the workyard waterworks)',['pulley'],'SfxFurnishings.pulleyCreak()',[['src/sfx_furnishings.js',"play('pulley'"]],'a sawtooth creak and square pawl ticks','replaced'),
 // ---------------- combat
 R('Combat','Swing: stab / slash / crush',['swing_stab','swing_slash','swing_crush'],'Sfx.swing(type)',[['src/combat_fx.js','s.swing(type)']],'band-passed noise whooshes','replaced'),
 R('Combat','Hit: slash / stab / crush (heavier on a big hit)',['hit_slash','hit_stab','hit_crush'],'Sfx.hitFlesh(type,big)',[['src/combat_fx.js','s.hitFlesh(atype,big)']],'a sine thud with a square click, 4 dB over the music','replaced'),
 R('Combat','The adventurer is hit',['hurt'],'Sfx.takeHit(big)',[['src/combat_fx.js','s.takeHit(big)']],'a sine thud, 4 dB over the music','replaced'),
 R('Combat','Block (0 on a humanoid or the adventurer)',['block'],'Sfx.block()',[['src/combat_fx.js','s.block()']],'triangle knocks','replaced'),
 R('Combat','Miss (0 on a beast)',['miss'],'Sfx.miss()',[['src/combat_fx.js','s.miss()']],'the block sound','new'),
 R('Combat','Bow: loose',['bow'],'Sfx.bowShoot()',[['src/combat_fx.js','s.bowShoot()']],'triangle and sine twangs','replaced'),
 R('Combat','Arrow hits / misses',['arrow_hit','arrow_miss'],'Sfx.arrowHit(ok)',[['src/combat_fx.js','s.arrowHit(ok)']],'noise and a square click','replaced'),
 R('Combat','Spell: gather, release, impact, splash (Gale Dart)',['spell_charge','spell_cast','spell_hit','spell_splash'],'Sfx.spellCharge / magicCast / magicHit / spellSplash',
  [['src/combat_fx.js','s.spellCharge()'],['src/combat_fx.js','s.magicCast()'],['src/combat_fx.js','s.magicHit()'],['src/combat_fx.js','s.spellSplash()']],'noise sweeps and sines','replaced'),
 R('Combat','A body falls',['body_fall'],'Sfx.bodyFall(at)',[['src/combat_fx.js','s.bodyFall(at(o))']],'a sine thud','replaced'),
 R('Combat','The adventurer dies (as they fall)',['player_death'],'Sfx.death()',[['src/combat_engine.js','Sfx.death()'],['src/game3_systems.js','Sfx.death();']],'a sawtooth 300 to 60 Hz, at the respawn','replaced'),
 // ---------------- creatures (the voices go by species: Sfx.species)
 R('Creatures','Rat: squeak (idle), bite, hurt, death',['rat_idle','rat_attack','rat_hurt','rat_death'],'Sfx.creature(npc,kind)',[['src/holm_sound.js',"s.creature(pick.n,'idle')"],['src/combat_fx.js',"voice(npc,'attack')"],['src/combat_fx.js',"voice(n,'hurt')"],['src/combat_fx.js',"voice(npc,'death')"]],'a generic snap; a sawtooth death','new'),
 R('Creatures','Goblin: mutter, attack, hurt, death',['goblin_idle','goblin_attack','goblin_hurt','goblin_death'],'Sfx.creature(npc,kind)',[['src/holm_sound.js',"s.creature(pick.n,'idle')"],['src/combat_fx.js',"if(sp==='goblin')voice(npc,'attack')"]],'a generic whoosh; a sawtooth death','new'),
 R('Creatures','Chicken: cluck, peck, squawk, death',['chicken_idle','chicken_attack','chicken_hurt','chicken_death'],'Sfx.creature(npc,kind)',[['src/holm_sound.js',"s.creature(pick.n,'idle')"],['src/combat_fx.js',"voice(npc,'attack')"]],'a generic snap; a sawtooth death','new'),
 R('Creatures','Cow: moo, butt, hurt, death',['cow_idle','cow_attack','cow_hurt','cow_death'],'Sfx.creature(npc,kind)',[['src/holm_sound.js',"s.creature(pick.n,'idle')"],['src/combat_fx.js',"if(sp==='cow'){voice(npc,'attack')"]],'a generic whoosh; a sawtooth death','new'),
 // ---------------- world
 R('World','Footsteps: grass, planks, stone (subtle, OFF by default: ?steps=1 or localStorage cr_sfx_steps=1)',['step_grass','step_wood','step_stone'],'Sfx.step(surface)',[['src/holm_sound.js','s.step(surf)']],'none','new'),
 R('World','Shore water (the sea, the creek)',['water_loop'],'HolmSound bed',[['src/holm_sound.js',"bed('water','water_loop'"]],'none','new'),
 R('World','Minnow Hollow pond: water, frog, duck, birds',['pond_loop','frog','duck','bird'],'HolmFishing ambient',[['src/holm_fishing.js',"Sfx.loop('pond_loop')"],['src/holm_fishing.js',"croak:'frog'"],['src/holm_fishing.js',"quack:'duck'"],['src/holm_fishing.js',"chirp:'bird'"]],'band noise; a sawtooth croak; a square quack','replaced'),
 R('World','Creakwheel Mill: the race, the paddles, the axle',['mill_rush','mill_slap','mill_creak'],'HolmMill',[['src/holm_mill.js',"Sfx.loop('mill_rush')"],['src/holm_mill.js',"Sfx.play('mill_slap'"],['src/holm_mill.js',"Sfx.play('mill_creak'"]],'a low-passed noise loop; a sawtooth creak','replaced'),
 R('World','The forge: the furnace\'s roar in the ore workings',['forge_loop'],'HolmSound bed',[['src/holm_sound.js',"bed('forge','forge_loop'"]],'none','new'),
 R('World','Tobin\'s ferry bell (three rings)',['bell'],'Sfx.bell(gain)',[['src/holm_island_anim.js','S.bell(v)']],'three sine partials','replaced'),
 R('World','Tobin\'s skiff: pushing off, the oars',['skiff_push','oar'],'Sfx.skiffPush() / Sfx.oar()',[['src/holm_island_anim.js','S.skiffPush()'],['src/holm_island_anim.js','S.oar()']],'none (the bell only)','new')
];
