#!/usr/bin/env node
/* Writes docs/rebuild/HOLM_SOUND_INVENTORY.md from tools/sfx_inventory.js (the events, before and after, the wiring) and
 * src/sfx_recipes.js (every sound and what it is made of). The evidence section between the markers
 * <!-- evidence --> and <!-- /evidence --> is kept as written. Run: node tools/sfx_inventory_doc.js */
'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.join(__dirname,'..'),OUT=path.join(ROOT,'docs','rebuild','HOLM_SOUND_INVENTORY.md');
const L=require('../src/sfx_lib.js');require('../src/sfx_recipes.js');
const INV=require('./sfx_inventory.js');
const esc=s=>String(s).replace(/\|/g,'\\|');
let keep='<!-- evidence -->\n_(filled in after the gates run)_\n<!-- /evidence -->';
try{const old=fs.readFileSync(OUT,'utf8').replace(/\r\n/g,'\n'),a=old.indexOf('<!-- evidence -->'),b=old.indexOf('<!-- /evidence -->');if(a>=0&&b>a)keep=old.slice(a,b+'<!-- /evidence -->'.length)}catch(e){}
const groups=[];INV.forEach(r=>{if(groups.indexOf(r.group)<0)groups.push(r.group)});
const count=s=>INV.filter(r=>r.status===s).length;
let md=`# Tutor's Holm sound inventory (sound pass, owner review 2026-09-29)

Branch \`holm-sound-fire\` (worktree \`CraftedRealms-Sound\`, from live \`16448ba3\`). Style bar: the 2004 client's short,
crisp sounds, our own designs (nothing copied), gentle under the music. This file is generated by
\`node tools/sfx_inventory_doc.js\` from \`tools/sfx_inventory.js\` and \`src/sfx_recipes.js\`; \`tools/test_sfx.js\` pins that
every sound here exists and every event is wired.

**Listen:** the sound board, \`http://localhost:8777/tools/sound_board.html\` (every sound with Play, Play x3 to hear the
variation, and Old where a sound was replaced; the three level-up candidates side by side).

## The owner's notes and what changed

| Owner (2026-09-29) | Now |
|---|---|
| "The sound effect when we open the relief chart ... feels very plain." | \`ui_map_open\`: the parchment unrolls (a swish, paper crinkles), settles on the table, and two soft harp notes ring. |
| "When I equip the hatchet, the noise it makes isn't really an equip noise." | \`equip_tool\`: a hand closing on an ash haft, the haft's wooden knock and the iron head's clunk. Every equip now sounds by material (tool, metal, wood, leather, cloth, arrows), and so does taking it off. |
| "Hitting the tree could be a different sound effect." | \`chop\`: the axe's bite, the oak's solid "thock" (wood modes), splinter chips; and it now lands on the swing's blow, not the 0.6 s tick (the 0.78 s chop swing drifted off it). Logs landing, the tree tipping and the tree landing are their own sounds. |
| "The fireworks looked good, but I wasn't too crazy about the noise it made when I leveled up." | The fireworks are unchanged. The sound is a new design: three candidates made, **A, a lute arpeggio**, picked (below). |
| "The door opening sound effect, I don't think that's been done." | \`door_open\` / \`door_close\` / \`door_locked\` on every door: the island's gates, the bakehouse store door, the Guide House doors, the mainland's doors, Lastlight; the bank vault's iron gate has its own. |
| "The sound of hitting a pickaxe on the rock is not correct ... when I actually break off a chunk of ore it should make a different style noise." | \`mine\`: a metallic ping of the pick head, a stone crack and a pinch of grit, on the swing's blow. \`ore_break\`: a different, bigger sound (the seam splitting, the chunk coming away and landing, pebbles running out). \`rock_empty\` when the rock is spent. |
| "The fires move a little bit fast ... a slower, more cozy fire, with occasionally a spark." | Every fire slower and softer, a small ember drifting up now and then, a quiet crackle by any fire (below). |

## How the sounds are made

- **All synthesized, no samples.** No recorded sound was downloaded or added, so \`THIRD_PARTY_ASSETS.md\` needs no entry.
  \`src/sfx_lib.js\` renders each recipe (\`src/sfx_recipes.js\`) in plain JavaScript into one mono buffer: noise bursts
  through resonant filters, pitch envelopes, modal "rings" (decaying sine modes for metal, wood, stone, a bell), plucked
  strings (Karplus-Strong), small formant voices (a glottal pulse train through three vowel resonators) for the
  creatures, stick-slip creaks (hinges, rope, timber), and scattered grains (debris, crackle, droplets). No square or
  sawtooth oscillator anywhere (the old sounds leaned on them).
- **Two audio nodes a sound.** The game plays each as one buffer source and one gain on the SFX bus: the Sound effects
  volume, a gentle high shelf (-3 dB over 7 kHz), a soft peak catcher, the speakers.
- **Variation.** Each sound keeps three variants (different seeds, rendered on first use; the common and the heavier ones
  render ahead in idle moments after the first click) and every play nudges pitch (about +-3%) and level (up to 12%
  quieter), and never repeats a variant back to back. The pitched musical cues (the harp chimes, the level-up, the chart's
  harp, the bell, the death sigh) keep one variant and are never pitch-nudged, so they stay in tune.
- **Mix.** Each recipe is set by its loudness (its loudest 50 ms) in dB against the 2004 music at the default volumes
  (measured offline with \`tools/music_render.js\`: short-term RMS about 0.05), never above -5 dB: UI ticks about -20,
  window sounds -17, skilling strokes -9, blows -5, creature idles -14, ambient beds -16 to -24, footsteps -24. The old
  set had blows at +4 dB over the music and UI ticks at -23.
- **Rules.** Nothing sounds before the first click, tap or key (the browser's autoplay rule: nothing is queued to burst
  out on the first gesture); nothing is built at volume 0; a sound with a place (a door, a falling tree, a creature)
  fades with distance.
- **Timing.** Sounds follow the existing ticks and animation events: the chop and the pickaxe on the swing's blow (the
  island's \`HolmSound\` reads the hand's lowest point, as the anvil's hammer already did; the tick plays them elsewhere),
  the tinderbox every other tick of the 7-tick kneel, the anvil on each hammer strike, the furnace at each smelting
  stroke, the bar and the item on their ticks, the tree landing on the fall animation's impact, the bell's three rings
  on the bell's swing. No tick, timing, roll or XP changed.

## Level-up: three candidates, one picked

- **A, lute arpeggio (picked)**: warm plucked strings C5 E5 G5 rising with the rockets and blooming into C6 and G5 as they
  burst (0.46 s), over a soft sine glow, a few tiny sparkles for the stars. Why: it is cozy and medieval (a string, not a
  synth beep), short (gone by 1.2 s), soft-edged, and it lines up with the fireworks, so the ear and the eye agree.
- **B, music box**: four tines and a closing dyad. Pretty but thin and tinkly, too close to a UI chime, and it can sound
  childish on the hundredth level.
- **C, horn call**: a soft two-note horn over a timpani thump. Reads as a fanfare: heavier and more "announcement" than cozy.
- Old: a firework whoosh, two pops, a crackle and a sine chime. All four are on the sound board.

## Cozy fires

- **Lit logs** (every campfire, the island's Blender campfire included): the flame's height used one sine at 3.2 Hz,
  +-25%; now three slow sines (about 0.5, 0.95 and 1.45 Hz) at about +-9% height, +-3% width and a slight lean, and the fire's
  light breathes with it (+-7%). \`src/cozy_fire.js\`.
- **Every Blender flicker clip** (the Guide House, bakehouse and Quest Lodge hearths, the bakehouse oven, the cavern
  furnace's glow, the storm cellar's wall torches): half speed and 0.65 weight (the swing blended toward the flame's rest
  shape), applied wherever an AnimationMixer makes the clip. 13 clips on the island.
- **The cavern wall torches** (a Blender curve on their brightness): read at half speed, the swing softened to 60%. The
  furnace's smelting flare steps at 4 Hz, not 7.5, and swings less.
- **Embers**: now and then (every 1.6 to 4.8 s per fire near the adventurer, sometimes two) a small ember rises about a
  tile, drifting and fading from yellow-orange to red; the Blender-rendered ember cell of
  \`assets/textures/fx/levelup_sparks_v1.png\`, tinted, additive. One THREE.Points for every fire: one draw call, a fixed
  pool of 48.
- **Crackle**: one quiet looping voice (\`fire_loop\`, a seamless 7 s loop) for the whole world, as loud as the nearest
  fire is close (full within 1.5 tiles, gone by 7); wall torches count, faintly.
- **Also fixed**: a burnt-out campfire left its PointLight in the scene (one more light for every fire ever lit, every
  lit shader paying for it); fire lights now come from a small pool and go dark when their fire does.
- **Off switch** for comparison: \`?cozyFire=0\` (the old flicker and speeds, no embers, no crackle).
- Not changed: the login screen's braziers (UI art in \`src/ui_osrs_kit.js\`, the UI agent's area).

## Hooks for the other agents (call these from your code)

Every name below is on the global \`Sfx\` (\`src/game3_systems.js\`); each plays its recipe through the SFX bus with the
gesture, volume and mute rules. Already called from today's code as listed in the inventory; for new code:

| Call | When |
|---|---|
| \`Sfx.doorOpen(at)\`, \`Sfx.doorClose(at)\`, \`Sfx.doorLocked(at)\` | a door swings open, shuts, or is tried and locked (\`at\`: {x,z}, optional) |
| \`Sfx.gateOpen(at)\`, \`Sfx.gateClose(at)\` | an iron gate |
| \`Sfx.stairs()\` | a flight of stairs is climbed (up or down) |
| \`Sfx.ladder('up'|'down')\`, \`Sfx.ropeClimb()\`, \`Sfx.ropeTie()\` | ladders and ropes |
| \`Sfx.windowOpen()\`, \`Sfx.windowClose()\` | a window or panel opens / closes (the make menu, a new interface) |
| \`Sfx.drink()\` (or \`Sfx.eat(id)\`, which gulps for a drinkable: ale, beer, tea, milk, juice, potions, brews, mead, cider) | beer and other drinks |
| \`Sfx.equip(id)\`, \`Sfx.unequip(id)\` | any new wear/remove path (the material is read from ITEMS) |
| \`Sfx.pickup()\`, \`Sfx.drop()\`, \`Sfx.bankDeposit()\`, \`Sfx.bankWithdraw()\` | items |
| \`Sfx.creature(npc,'idle'|'attack'|'hurt'|'death')\` | a rat, goblin, chicken or cow speaks (by \`Sfx.species(npc)\`) |
| \`Sfx.prospect()\` | when a Prospect option is added |
| \`Sfx.play(id,{gain,rate,delay,at,range})\`, \`Sfx.loop(id)\` | any recipe by id; a looping bed ({setGain, stop}) |

## The inventory (${INV.length} events: ${count('replaced')} replaced, ${count('new')} new, ${count('not in game')} not in the game yet, ${count('candidate')} board-only)

`;
groups.forEach(g=>{md+=`### ${g}\n\n| Event | Sound(s) | Before | Now | Wired at |\n|---|---|---|---|---|\n`;
 INV.filter(r=>r.group===g).forEach(r=>{md+=`| ${esc(r.event)} | ${r.sounds.map(s=>'`'+s+'`').join(', ')} | ${esc(r.before)} | ${r.status}${r.note?': '+esc(r.note):''} | ${r.wired.map(w=>'`'+w[0].replace(/^src\//,'')+'`').filter((v,i,a)=>a.indexOf(v)===i).join(', ')} |\n`});md+='\n'});
md+=`## Every sound and what it is made of (${L.ORDER.length})\n\nLoudness: dB against the music (the loudest 50 ms). Old: the sound it replaced (on the sound board).\n\n| Sound | Name | dB | Made of | Old |\n|---|---|---|---|---|\n`;
L.ORDER.forEach(id=>{const d=L.DEFS[id];md+=`| \`${id}\` | ${esc(d.label)} | ${d.lvl} | ${esc(d.made)} | ${esc(d.old||'(none)')} |\n`});
md+=`\n## Evidence and gates\n\n${keep}\n`;
fs.writeFileSync(OUT,md.replace(/\r?\n/g,'\r\n'));console.log('[DOC] '+path.relative(ROOT,OUT)+': '+INV.length+' events, '+L.ORDER.length+' sounds');
