/* Design-study attachment. The walking study deliberately retains its measured geometry. */
export async function loadLodgeLedger(THREE,GLTFLoader,lodge,baseSha){
 if(baseSha!=='6de1fd292bfdd0f3dd51bf0031297f8905eb72ff19a8ed9be759b7f4f738140b')throw Error('Ledger host geometry drift');
 const base='../.studio-workspaces/holm-story-ledger-v1/candidates/',response=await fetch(base+'contract.json',{cache:'no-store'});if(!response.ok)throw Error('Ledger contract unavailable');const contract=await response.json();
 const r=await fetch(base+'ledger.glb',{cache:'no-store'});if(!r.ok)throw Error('Ledger model unavailable');const bytes=await r.arrayBuffer(),sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(v=>v.toString(16).padStart(2,'0')).join('');if(sha!==contract.glbSha256)throw Error('Ledger byte drift');
 const old=lodge.getObjectByName('Lodge_FurnishingBay_Original_parchment');if(!old?.isMesh)throw Error('Measured bay parchment missing');lodge.updateMatrixWorld(true);const support=new THREE.Box3().setFromObject(old,true),size=support.getSize(new THREE.Vector3());
 if(Math.abs(size.x-.45)>.00002||Math.abs(size.z-.65)>.00002)throw Error('Ledger host footprint drift');
 const g=await new Promise((resolve,reject)=>new GLTFLoader().parse(bytes,'',resolve,reject));g.scene.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(g.scene,true),dims=box.getSize(new THREE.Vector3());if(Math.abs(box.min.y)>.00001||dims.x>size.x||dims.z>size.z||dims.y>.12||!g.scene.getObjectByName('story_ledger'))throw Error('Ledger fit failed');
 const table=lodge.getObjectByName('Lodge_FurnishingBay_Warm_oak');if(!table?.isMesh)throw Error('Bay table support missing');const tableBox=new THREE.Box3().setFromObject(table,true);if(Math.abs(tableBox.max.y-support.min.y)>.03)throw Error('Ledger table support drift');const anchor=support.getCenter(new THREE.Vector3());anchor.y=tableBox.max.y;lodge.worldToLocal(anchor);g.scene.position.copy(anchor);g.scene.name='Lodge_StoryLedger';g.scene.traverse(o=>{if(o.isMesh)o.castShadow=o.receiveShadow=true});lodge.add(g.scene);old.userData.replacedByLedger=true;old.visible=false;
 console.info('[LODGE_LEDGER_STUDIO]',JSON.stringify({sha256:sha,position:anchor.toArray(),dimensions:dims.toArray(),triangles:contract.triangleCount}));return {root:g.scene,anchor,triangles:contract.triangleCount};
}
