/* Writes docs/rebuild/HOLM_PLAYTHROUGHS.md from scratchpad/holm_island_playthrough/runs.jsonl (owner acceptance:
 * at least 10 complete real-input playthroughs of the island, everything working). Every run is listed; the count of
 * complete zero-error runs since the last failure is what the acceptance item reads.
 * Run: node tools/summarize_holm_playthroughs.js */
'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..'),SRC=path.join(ROOT,'scratchpad/holm_island_playthrough/runs.jsonl');
const runs=fs.existsSync(SRC)?fs.readFileSync(SRC,'utf8').trim().split('\n').filter(Boolean).map(l=>JSON.parse(l)):[];
const good=r=>r.status==='complete'&&!(r.errors||[]).length;
let streak=0;for(let i=runs.length-1;i>=0&&good(runs[i]);i--)streak++;
const total=runs.filter(good).length,mins=runs.filter(good).map(r=>r.minutes);
const avg=mins.length?(mins.reduce((a,b)=>a+b,0)/mins.length).toFixed(1):'-';
const lines=['# Tutor\'s Holm complete playthroughs','',
 'Owner acceptance: at least 10 complete playthroughs of the finished island with everything working, by real input.',
 'Driver: `tools/qa_holm_island_playthrough.js` (fresh adventurer, all 18 lessons in order with no granted progress,',
 'every tutor talked to, three save/reloads, burnt fish and missed spells retried, ferry departure).',
 'Generated by `tools/summarize_holm_playthroughs.js` from `scratchpad/holm_island_playthrough/runs.jsonl`.','',
 '**Complete zero-error runs: '+total+' of '+runs.length+'; current unbroken streak: '+streak+'; average '+avg+' min (driver pace).**','',
 '| # | when (UTC) | status | minutes | lessons | page errors | note |','|---|---|---|---|---|---|---|'];
runs.forEach((r,i)=>lines.push('| '+(i+1)+' | '+String(r.at||'').replace('T',' ').slice(0,16)+' | '+r.status+' | '+r.minutes+' | '+r.lessons+'/18 | '+(r.errors||[]).length+' | '+String(r.note||'').replace(/\|/g,'/').slice(0,120)+' |'));
lines.push('','Per-lesson seconds of the latest complete run:','');
const last=[...runs].reverse().find(good);if(last)lines.push('```',Object.entries(last.perLessonSeconds||{}).map(([k,v])=>k+' '+v+'s').join('  '),'```');
fs.writeFileSync(path.join(ROOT,'docs/rebuild/HOLM_PLAYTHROUGHS.md'),lines.join('\n')+'\n');
console.log('[PLAYTHROUGHS] '+total+'/'+runs.length+' complete, streak '+streak);
