#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const C=require('../src/fishing_edge_u5_contract.js');
let pass=0,fail=0,rows=[];
function ok(name,value){if(value){pass++;rows.push({name,pass:true});}else{fail++;rows.push({name,pass:false});console.error('[U5 CONTRACT] FAIL',name);}}
function inv(slots,capacity){return {slots:slots,capacity:capacity===undefined?slots.length:capacity};}
let s=C.u5CreateSave();
ok('fresh save has no active operation',s.active===null);
ok('fresh save remembers no catches',s.firstCatchComplete===false&&s.appliedOps.length===0);
ok('first catch timing is deterministic and fast',C.u5WaitSeconds(s,'anything')===.70);
ok('missing net is rejected',C.u5BeginOperation(s,'a',inv([null],1),'seed').reason==='requires small net');
ok('full pack is rejected',C.u5BeginOperation(s,'a',inv(['fishing_net'],1),'seed').reason==='inventory full');
let begin=C.u5BeginOperation(s,'u5-op-1',inv(['fishing_net',null],2),'seed');s=begin.save;
ok('valid operation begins',begin.ok&&s.active.state==='casting');
ok('first operation records tutorial timing',s.active.firstTutorialCatch&&s.active.waitSeconds===.70);
ok('caller save was not mutated',C.u5CreateSave().active===null);
let copy=C.u5CloneSave(s);copy.active.state='changed';
ok('clone does not alias active state',s.active.state==='casting');
s=C.u5Advance(s,'CAST_COMPLETE',inv(['fishing_net',null],2)).save;
ok('cast advances to waiting',s.active.state==='waiting');
s=C.u5Advance(s,'BITE',inv(['fishing_net',null],2)).save;
ok('bite becomes readable state',s.active.state==='bite');
s=C.u5Advance(s,'NET',inv(['fishing_net',null],2)).save;
ok('net action advances to catching',s.active.state==='catching');
let committed=C.u5Advance(s,'CATCH_COMPLETE',inv(['fishing_net',null],2));s=committed.save;
ok('catch commits one reward',committed.effects.length===1&&committed.effects[0].id==='raw_perch');
ok('reward carries exact fishing xp',committed.effects[0].skill==='fishing'&&committed.effects[0].xp===28);
ok('operation id is banked once',s.appliedOps.join('|')==='u5-op-1');
ok('first tutorial catch is complete',s.firstCatchComplete===true);
let replay=C.u5Advance(s,'CATCH_COMPLETE',inv(['fishing_net',null],2));
ok('replayed commit pays nothing',replay.effects.length===0&&replay.save.appliedOps.length===1);
s=C.u5Advance(s,'SETTLED',inv(['fishing_net',null],2)).save;
ok('settled clears active operation',s.active===null);
ok('rewarded operation id cannot restart',C.u5BeginOperation(s,'u5-op-1',inv(['fishing_net',null],2),'x').reason==='operation id already rewarded');
let laterA=C.u5WaitSeconds(s,'fixed-seed'),laterB=C.u5WaitSeconds(s,'fixed-seed');
ok('later timing is seeded and repeatable',laterA===laterB&&laterA>=1.25&&laterA<=2.75);
let interrupted=C.u5BeginOperation(s,'u5-op-2',inv(['fishing_net',null],2),'x').save;
interrupted=C.u5Advance(interrupted,'CAST_COMPLETE',inv(['fishing_net',null],2)).save;
let reset=C.u5Advance(interrupted,'INTERRUPT',inv(['fishing_net',null],2));
ok('interruption clears active operation',reset.save.active===null);
ok('interruption awards nothing',reset.effects.length===1&&reset.effects[0].type==='reset'&&reset.save.appliedOps.length===1);
let fullAtCommit=C.u5BeginOperation(s,'u5-op-3',inv(['fishing_net',null],2),'x').save;
fullAtCommit=C.u5Advance(fullAtCommit,'CAST_COMPLETE',inv(['fishing_net',null],2)).save;
fullAtCommit=C.u5Advance(fullAtCommit,'BITE',inv(['fishing_net',null],2)).save;
fullAtCommit=C.u5Advance(fullAtCommit,'NET',inv(['fishing_net',null],2)).save;
let rejected=C.u5Advance(fullAtCommit,'CATCH_COMPLETE',inv(['fishing_net','logs'],2));
ok('full pack at commit pays nothing',rejected.effects[0].type==='message'&&rejected.save.appliedOps.length===1);
let many=C.u5CreateSave();many.firstCatchComplete=true;many.appliedOps=Array.from({length:32},(_,i)=>'old-'+i);
let b=C.u5BeginOperation(many,'new-op',inv(['fishing_net',null],2),'seed').save;
b=C.u5Advance(b,'CAST_COMPLETE',inv(['fishing_net',null],2)).save;b=C.u5Advance(b,'BITE',inv(['fishing_net',null],2)).save;
b=C.u5Advance(b,'NET',inv(['fishing_net',null],2)).save;b=C.u5Advance(b,'CATCH_COMPLETE',inv(['fishing_net',null],2)).save;
ok('ledger remains capped',b.appliedOps.length===32&&b.appliedOps[31]==='new-op');
ok('unknown event is inert',C.u5Advance(b,'NOPE',inv(['fishing_net',null],2)).effects.length===0);
const result={assetId:'workyard_fishing_edge_u5_v1',verdict:fail?'FAIL':'PASS',pass,fail,assertions:rows};
const out=path.join(__dirname,'..','scratchpad','workyard_fishing_edge_u5_v1','contract_test_result.json');
fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(result,null,2));
console.log(`[U5 CONTRACT] ${result.verdict} ${pass}/${pass+fail}`);process.exitCode=fail?1:0;
